import numpy as np
np.random.seed(0)
A = np.random.randint(1, 21, size=5)
B = np.random.randint(1, 21, size=5)
print("A + B =", A + B)
print("A - B =", A - B)
print("A * B =", A * B)
print("A / B =", A.astype(float) / B.astype(float))
dot_prod = np.dot(A, B)
print("Dot product (A · B) =", dot_prod)
mean_A = A.mean()
median_A = np.median(A)
std_A = A.std()
var_A = A.var()
print("Statistics for A:")
print(f"  Mean               = {mean_A:.2f}")
print(f"  Median             = {median_A}")
print(f"  Standard Deviation = {std_A:.2f}")
print(f"  Variance           = {var_A:.2f}")
max_val = B.max()
min_val = B.min()
max_idx = B.argmax()
min_idx = B.argmin()
print("Array B extremes:")
print(f"  Maximum value = {max_val} at index {max_idx}")
print(f"  Minimum value = {min_val} at index {min_idx}")